//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface _SPPtrDict : NSObject
{
    struct __CFDictionary *_tagSet;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)setObject:(id)arg1 forKey:(void *)arg2;
- (void)removeObjectForKey:(void *)arg1;
- (id)objectForKey:(void *)arg1;
- (void)dealloc;
- (id)init;

@end

