//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableDictionary, NSString, SDUpdatesFile;

@interface SDClient : NSObject
{
    NSMutableDictionary *_queriesByExternId;
    _Bool _updating;
    NSString *_applicationDisplayID;
    NSString *_category;
    SDUpdatesFile *_updatesFile;
    NSMutableDictionary *_contentIndices;
    NSDate *_timer;
    NSString *_lastQuery;
}

+ (void)registerMessageHandlersWithServer:(id)arg1;
+ (id)clientForConnection:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancelQueryWithExternalID:(unsigned int)arg1;
- (void)getImageDataForImageIdentifier:(id)arg1 domain:(unsigned int)arg2 size:(struct CGSize)arg3 callback:(CDUnknownBlockType)arg4;
- (void)getImageDataForResultIdentifier:(unsigned long long)arg1 domain:(unsigned int)arg2 size:(struct CGSize)arg3 callback:(CDUnknownBlockType)arg4;
- (void)addAndStartQuery:(id)arg1;
- (void)removeActiveQuery:(id)arg1;
- (void)_endCrashHandling;
- (void)_beginCrashHandlingForStore:(id)arg1 andQuery:(id)arg2;

@end

