//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SDEventHandlerProvider.h"

@class NSObject<OS_dispatch_queue>;

@interface SDMigrationMonitor : NSObject <SDEventHandlerProvider>
{
    _Bool _extensionsLoaded;
    _Bool _reindexNeeded;
    NSObject<OS_dispatch_queue> *_synchronizationQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *synchronizationQueue; // @synthesize synchronizationQueue=_synchronizationQueue;
@property _Bool reindexNeeded; // @synthesize reindexNeeded=_reindexNeeded;
@property _Bool extensionsLoaded; // @synthesize extensionsLoaded=_extensionsLoaded;
- (void).cxx_destruct;
- (void)_makeExtensionsReindex;
- (void)registerHandlerWithEventMonitor:(id)arg1;
- (void)extensionsLoaded:(id)arg1;
- (void)dealloc;
- (id)init;

@end

