//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString, SDSearchQuery, SPContentResult, SPFeedback;

@protocol SDModernSearchDatastore <NSObject>
- (NSString *)displayIdentifierForDomain:(unsigned int)arg1;
- (NSArray *)searchDomains;

@optional
@property(retain, nonatomic) NSDictionary *category_stats;
- (void)shrink;
- (void)imageDataForIdentifier:(NSString *)arg1 domain:(unsigned int)arg2 size:(struct CGSize)arg3 completion:(void (^)(NSData *))arg4;
- (void)imageDataForResultIdentifier:(unsigned long long)arg1 domain:(unsigned int)arg2 size:(struct CGSize)arg3 completion:(void (^)(NSData *))arg4;
- (id <SDSearchToken>)performQuery:(SDSearchQuery *)arg1;
- (_Bool)onlyDefaultSearch;
- (_Bool)offersDefaultSearch;
- (void)sendFeedback:(SPFeedback *)arg1;
- (SPContentResult *)resultForIdentifier:(NSString *)arg1 domain:(unsigned int)arg2;
- (NSString *)categoryForDomain:(unsigned int)arg1;
- (double)timeOutForDomain:(unsigned int)arg1;
- (_Bool)wantsEveryResultInItsOwnSection;
- (void)shutDown;
- (_Bool)coolDown;
- (void)preheat;
- (void)deactivate;
- (void)activate;
@end

