//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPSearchQuery.h"

#import "SPSearchResultsPipe.h"

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_source>, NSString, SPXPCConnection, SPXPCMessage;

@interface SDSearchQuery : SPSearchQuery <SPSearchResultsPipe>
{
    SPXPCConnection *_connection;
    unsigned int _externalID;
    unsigned long long _stopWaitTime;
    NSObject<OS_dispatch_source> *_timer;
    NSMutableArray *_waitingDomains;
    NSArray *_bottomRankedCategories;
    _Bool _didSendTopHits;
    _Bool _didSendResults;
    _Bool _isZKW;
    NSDictionary *_category_stats;
    NSArray *_parsecCategoryOrdering;
    NSMutableDictionary *_categoryToResultMapping;
    SPXPCMessage *_message;
    unsigned long long _startTime;
    NSString *_fbq;
    NSString *_web_fbq;
    NSMutableArray *_tokens;
    NSMutableArray *_slowTokens;
    NSMutableDictionary *_sections;
}

@property(retain, nonatomic) NSMutableDictionary *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) NSMutableArray *slowTokens; // @synthesize slowTokens=_slowTokens;
@property(retain, nonatomic) NSMutableArray *tokens; // @synthesize tokens=_tokens;
@property(readonly) NSString *web_fbq; // @synthesize web_fbq=_web_fbq;
@property(readonly) NSString *fbq; // @synthesize fbq=_fbq;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
@property(nonatomic) _Bool isZKW; // @synthesize isZKW=_isZKW;
@property(retain, nonatomic) SPXPCMessage *message; // @synthesize message=_message;
@property(readonly, nonatomic) unsigned int externalID; // @synthesize externalID=_externalID;
@property(readonly, nonatomic) SPXPCConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSMutableDictionary *categoryToResultMapping; // @synthesize categoryToResultMapping=_categoryToResultMapping;
@property(retain, nonatomic) NSArray *parsecCategoryOrdering; // @synthesize parsecCategoryOrdering=_parsecCategoryOrdering;
@property(retain, nonatomic) NSDictionary *category_stats; // @synthesize category_stats=_category_stats;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)onlyDefaultSearch;
- (_Bool)offersDefaultSearch;
- (id)initWithSearchString:(id)arg1 keyboardLanguage:(id)arg2 keyboardPrimaryLanguage:(id)arg3 forSearchDomains:(id)arg4 disabledBundles:(id)arg5 externalID:(unsigned int)arg6 connection:(id)arg7;
- (_Bool)storeCompletedSearch:(id)arg1;
- (void)storeWillComplete:(id)arg1;
- (void)setTimeout:(float)arg1;
- (void)domainCompletedSearch:(unsigned int)arg1;
- (void)sendFinishedDomains;
- (void)subcategorize:(id)arg1;
- (void)makeTopHits:(id)arg1 maxTopHitCount:(long long)arg2;
- (void)sendResultsForKeys:(id)arg1 toSendSections:(id)arg2;
- (id)orderedCategories:(id)arg1;
- (void)getSmartRankedDomains:(id *)arg1 bottom:(id *)arg2 blacklisted:(id *)arg3;
- (id)getBagCEPBlacklist:(id)arg1;
- (_Bool)isFoundInCache:(id)arg1;
- (void)appendSection:(id)arg1;
- (void)appendSection:(id)arg1 toSerializerDomain:(unsigned int)arg2;
- (void)appendResults:(id)arg1 toSerializerDomain:(unsigned int)arg2;
- (void)appendResults:(id)arg1;
- (void)appendSerializer:(id)arg1 toSerializerDomain:(unsigned int)arg2;
- (void)sendQueryReset;
- (void)sendQueryCompleted;
- (void)sendError:(id)arg1;
- (void)sendResults:(id)arg1;
- (void)sendData:(id)arg1;
- (void)cancel;
- (void)addSlowQueryToken:(id)arg1;
- (void)addQueryToken:(id)arg1;
- (void)queryFinishedWithError:(id)arg1;

@end

