//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SDModernSearchDatastore.h"

@class NSDictionary, NSString;

@interface SPCalculationDatastore : NSObject <SDModernSearchDatastore>
{
}

+ (void)initialize;
- (_Bool)onlyDefaultSearch;
- (_Bool)offersDefaultSearch;
- (id)searchDomains;
- (id)displayIdentifierForDomain:(unsigned int)arg1;
- (void)doUnitConversionWithQuery:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)doCalculationWithQuery:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (id)performQuery:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSDictionary *category_stats;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

