//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface SPCoreSpotlightTask : NSObject
{
    struct __CFArray *_jobs;
    NSMutableArray *_indexes;
}

- (void).cxx_destruct;
- (void)removeJob:(struct __SIJobRef *)arg1;
- (void)addJob:(struct __SIJobRef *)arg1 forIndex:(id)arg2;
- (void)cancel;
- (void)dealloc;
- (id)init;

@end

