//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SDSearchToken.h"

@class NSDictionary, NSObject<OS_dispatch_queue>, NSString, SDSearchQuery, SPCoreSpotlightDatastore, SPCoreSpotlightTask;

@interface SPCoreSpotlightQueryTask : NSObject <SDSearchToken>
{
    _Bool _done;
    _Bool _live;
    _Bool _canceled;
    SPCoreSpotlightTask *_job;
    SPCoreSpotlightDatastore *_store;
    NSObject<OS_dispatch_queue> *_queue;
    SDSearchQuery *_resultPipe;
}

@property _Bool canceled; // @synthesize canceled=_canceled;
@property _Bool live; // @synthesize live=_live;
@property _Bool done; // @synthesize done=_done;
@property(nonatomic) __weak SDSearchQuery *resultPipe; // @synthesize resultPipe=_resultPipe;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly) SPCoreSpotlightDatastore *store; // @synthesize store=_store;
@property(retain, nonatomic) SPCoreSpotlightTask *job; // @synthesize job=_job;
- (void).cxx_destruct;
- (void)finish;
- (void)begin;
- (void)cancel;
- (id)initWithStore:(id)arg1 resultPipe:(id)arg2;

// Remaining properties
@property(retain, nonatomic) NSDictionary *category_stats;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

