//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable, NSMutableArray, NSMutableSet, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString, SPCoreSpotlightIndexer, _SPPtrDict;

@interface SPConcreteCoreSpotlightIndexer : NSObject
{
    unsigned int _maintenanceOperations;
    unsigned long long _dirty_time;
    int *_cancelPtr;
    int _suspended;
    NSMapTable *_checkedInClients;
    NSMutableSet *_knownClients;
    NSMutableSet *_reindexAllDelegateBundleIDs;
    double _lastPreheat;
    double _lastTTLPass;
    SPCoreSpotlightIndexer *_owner;
    struct __SI *_index;
    struct __SIResultQueue *_resultQueue;
    NSObject<OS_dispatch_queue> *_indexQueue;
    NSObject<OS_dispatch_queue> *_firstUnlockQueue;
    _SPPtrDict *_tagSet;
    NSString *_dataclass;
    NSObject<OS_dispatch_source> *_idleTimer;
    NSMutableArray *_outstandingMaintenance;
}

+ (id)_stateInfoAttributeNameWithClientStateName:(id)arg1;
+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *outstandingMaintenance; // @synthesize outstandingMaintenance=_outstandingMaintenance;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *idleTimer; // @synthesize idleTimer=_idleTimer;
@property(retain, nonatomic) NSString *dataclass; // @synthesize dataclass=_dataclass;
@property(retain, nonatomic) _SPPtrDict *tagSet; // @synthesize tagSet=_tagSet;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *firstUnlockQueue; // @synthesize firstUnlockQueue=_firstUnlockQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *indexQueue; // @synthesize indexQueue=_indexQueue;
@property(nonatomic) struct __SIResultQueue *resultQueue; // @synthesize resultQueue=_resultQueue;
@property(nonatomic) struct __SI *index; // @synthesize index=_index;
@property(nonatomic) __weak SPCoreSpotlightIndexer *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (void)powerStateChanged;
- (void)attributesForBundleId:(id)arg1 identifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchAttributes:(id)arg1 bundleID:(id)arg2 identifiers:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)imageDataForBundleId:(id)arg1 identifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)userPerformedAction:(id)arg1 withItem:(id)arg2 forBundleID:(id)arg3;
- (void)changeStateOfSearchableItemsWithUIDs:(id)arg1 toState:(long long)arg2 forBundleID:(id)arg3;
- (void)fetchLastClientStateForBundleID:(id)arg1 clientStateName:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)deleteSearchableItemsSinceDate:(id)arg1 forBundleID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)deleteAllSearchableItemsForBundleID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteSearchableItemsWithDomainIdentifiers:(id)arg1 forBundleID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)deleteItemsForEnumerator:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteItemsForQuery:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)willModifySearchableItemsWithIdentifiers:(id)arg1 forBundleID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)cancelQuery:(struct __SIJobRef *)arg1;
- (struct __SIJobRef *)startQuery:(id)arg1 options:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)indexSearchableItems:(id)arg1 deleteSearchableItemsWithIdentifiers:(id)arg2 clientState:(id)arg3 clientStateName:(id)arg4 forBundleID:(id)arg5 options:(long long)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)indexSearchableItems:(id)arg1 deleteSearchableItemsWithIdentifiers:(id)arg2 clientState:(id)arg3 forBundleID:(id)arg4 options:(long long)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)indexFromBundle:(id)arg1 options:(long long)arg2 items:(id)arg3 itemsText:(id)arg4 clientState:(id)arg5 clientStateName:(id)arg6 deletes:(id)arg7 completionHandler:(CDUnknownBlockType)arg8;
- (void)_setClientState:(id)arg1 clientStateName:(id)arg2 forBundleID:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)preheat;
- (void)suspendIndexForDeviceLock;
- (void)readyIndex:(_Bool)arg1;
- (void)resumeIndex;
- (void)closeIndex;
- (void)issueRepair;
- (void)issueMerge;
- (void)issueSplit;
- (void)shrink;
- (void)coolDown:(id)arg1;
- (_Bool)commitUpdates:(id)arg1;
- (void)addCompletedBundleIDs:(id)arg1 forIndexerTask:(id)arg2;
- (void)fetchAllCompletedBundleIDsForIndexerTask:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (_Bool)reindexAllStarted;
- (void)finishReindexAll;
- (void)startReindexAll;
- (void)performIndexerTask:(id)arg1 withIndexDelegatesAndCompletionHandler:(CDUnknownBlockType)arg2;
- (void)performIndexerTask:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)addClients:(id)arg1;
- (void)checkInWithBundleID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)clientDidCheckin:(id)arg1 service:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (int)openIndex:(_Bool)arg1;
- (int)openIndex:(_Bool)arg1 shouldReindexAll:(_Bool)arg2;
- (void)revokeExpiredItems:(id)arg1;
- (void)removeExpiredItemsForBundleId:(id)arg1 group:(id)arg2;
- (void)indexFinishedDrainingJournal;
- (void)indexFinishedDrainingJournal:(id)arg1;
- (void)scheduleMaintenance:(CDUnknownBlockType)arg1 description:(id)arg2 forDakeWake:(_Bool)arg3;
- (void)performActivity:(id)arg1;
- (id)_indexPath;
- (void)addKnownClient:(id)arg1;
- (void)dirty;
- (id)initWithQueue:(id)arg1 protectionClass:(id)arg2 cancelPtr:(int *)arg3;
- (void)processResultsFromQueue:(struct __SIResultQueue *)arg1;
- (id)getPropertyForKey:(id)arg1;
- (void)setProperty:(id)arg1 forKey:(id)arg2;
- (void)dealloc;

@end

