//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPContentResult.h"

@class NSDate, NSString;

@interface SPCoreSpotlightContentResult : SPContentResult
{
    NSString *_relatedUniqueIdentifier;
    unsigned long long _buddyScore;
    NSString *_itemIdentifier;
    NSDate *_lastUsedDate;
    NSDate *_interestingDate;
    NSString *_domainIdentifier;
    long long _incomingCount;
    long long _outgoingCount;
}

@property long long outgoingCount; // @synthesize outgoingCount=_outgoingCount;
@property long long incomingCount; // @synthesize incomingCount=_incomingCount;
@property(retain) NSString *domainIdentifier; // @synthesize domainIdentifier=_domainIdentifier;
@property(retain) NSDate *interestingDate; // @synthesize interestingDate=_interestingDate;
@property(retain) NSDate *lastUsedDate; // @synthesize lastUsedDate=_lastUsedDate;
@property(retain) NSString *itemIdentifier; // @synthesize itemIdentifier=_itemIdentifier;
@property unsigned long long buddyScore; // @synthesize buddyScore=_buddyScore;
@property(retain) NSString *relatedUniqueIdentifier; // @synthesize relatedUniqueIdentifier=_relatedUniqueIdentifier;
- (void).cxx_destruct;

@end

