//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SDModernSearchDatastore.h"

@class NSCalendar, NSDateFormatter, NSDateIntervalFormatter, NSDictionary, NSNumber, NSNumberFormatter, NSObject<OS_dispatch_queue>, NSString;

@interface SPCoreSpotlightDatastore : NSObject <SDModernSearchDatastore>
{
    _Bool _loadedApps;
    int _changedToken;
    NSObject<OS_dispatch_queue> *_queryQueue;
    NSNumberFormatter *_numberFormatter;
    NSCalendar *_calendar;
    NSDateFormatter *_dateFormatter;
    NSDateFormatter *_allDayDateFormatter;
    NSDateIntervalFormatter *_dateIntervalFormatter;
    _Bool _explicitContentAllowed;
    NSNumber *_maxTVShowRating;
    NSNumber *_maxMovieRating;
    _Bool _activated;
}

+ (id)rankingTerms:(id)arg1;
+ (id)attributeNameArray;
+ (void)initialize;
- (void).cxx_destruct;
- (void)imageDataForIdentifier:(id)arg1 domain:(unsigned int)arg2 size:(struct CGSize)arg3 completion:(CDUnknownBlockType)arg4;
- (void)sendFeedback:(id)arg1;
- (id)displayIdentifierForDomain:(unsigned int)arg1;
- (id)searchDomains;
- (id)_searchDomainsSet;
- (id)performQuery:(id)arg1;
- (void)processSection:(id)arg1;
- (void)makeCoreSpotlightResult:(id)arg1 dataclass:(id)arg2 query:(id)arg3 score:(id)arg4 utiType:(id)arg5 bundleID:(id)arg6 corespotlightSection:(id)arg7 contactsSection:(id)arg8 voiceSection:(id)arg9 calendarSection:(id)arg10 remindersSection:(id)arg11 notesSection:(id)arg12 pseudoContactsSection:(id)arg13;
- (id)attributeMapToUserActivityResults:(id)arg1 toResults:(id)arg2 bundleID:(id)arg3 identifiers:(id)arg4;
- (id)makeUserActivityResultsForBundleID:(id)arg1 fromIdentifiers:(id)arg2;
- (void)_populateUserActivityResult:(id)arg1 values:(id)arg2 utiType:(id)arg3 bundleID:(id)arg4;
- (void)processGenericItem:(id)arg1 dataclass:(id)arg2 values:(id)arg3 utiType:(id)arg4 bundleID:(id)arg5 corespotlightSection:(id)arg6 contactsSection:(id)arg7 voiceSection:(id)arg8 calendarSection:(id)arg9 remindersSection:(id)arg10 notesSection:(id)arg11;
- (void)setSearchURLForResult:(id)arg1 identifier:(id)arg2 domain:(int)arg3 bundleID:(id)arg4 query:(id)arg5;
- (void)setPromisedDocumentDataForResult:(id)arg1;
- (void)setupGenericItem:(id)arg1 dataclass:(id)arg2 values:(id)arg3 utiType:(id)arg4 bundleID:(id)arg5;
- (_Bool)_playButtonSupportedForBundleID:(id)arg1;
- (void)addActionButton:(id)arg1 contentType:(id)arg2 contentTypeTree:(id)arg3 values:(id)arg4;
- (_Bool)_contentType:(id)arg1 orContentTypeTree:(id)arg2 representsType:(id)arg3;
- (_Bool)documentIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)contactIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)messageIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)reminderIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)eventIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)bookIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)playlistOrAlbumIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)audioOrVideoIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)audioIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (_Bool)imageIsRepresentedByContentType:(id)arg1 orContentTypeTree:(id)arg2;
- (void)addNavButton:(id)arg1 latitude:(id)arg2 longitude:(id)arg3;
- (void)addCallButton:(id)arg1 phoneNumber:(id)arg2;
- (void)addPlayButton:(id)arg1 adamID:(id)arg2;
- (void)makePersonResult:(id)arg1 identifier:(id)arg2 query:(id)arg3 result:(id)arg4;
- (id)makeDateBasedResult:(id)arg1 result:(id)arg2;
- (void)makeApplicationResult:(id)arg1 dataclass:(id)arg2 score:(id)arg3 appSection:(id)arg4;
- (void)makeMessagesResult:(id)arg1 dataclass:(id)arg2 query:(id)arg3 score:(id)arg4 messagesSection:(id)arg5;
- (void)makeMailResult:(id)arg1 dataclass:(id)arg2 score:(id)arg3 searchString:(id)arg4 mailSection:(id)arg5;
- (void)deactivate;
- (void)activate;
- (void)updateApplications;
- (void)primeApplications;
- (void)dealloc;
- (void)_updateCalendarAndFormatterLocale;
- (id)init;
- (void)localeChanged:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSDictionary *category_stats;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

