//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MDIndexer.h"

@class NSDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSObject<OS_xpc_object>, NSSet, NSString;

@interface SPCoreSpotlightIndexer : NSObject <MDIndexer>
{
    int cancelFlags[4];
    double _lastUpdateTime;
    _Bool _deviceFirstUnlockedInMKB;
    _Bool _deviceFirstUnlockedInSB;
    int _springBoardLockStateNotifyToken;
    int _keybagLockStateNotifyToken;
    id <CSIndexExtensionDelegate> extensionDelegate;
    NSObject<OS_dispatch_source> *_idleTimer;
    NSObject<OS_dispatch_queue> *_indexQueue;
    NSObject<OS_dispatch_queue> *_reindexAllQueue;
    unsigned long long _dataMigrationStage;
    NSDictionary *_concreteIndexers;
    unsigned long long _dirty_time;
    NSObject<OS_xpc_object> *_expirationActivity;
    NSObject<OS_dispatch_queue> *_firstUnlockQueue;
    NSObject<OS_dispatch_source> *_firstUnlockTimer;
    id <NSObject> _dataMigrationStartObserver;
    id <NSObject> _dataMigrationFinishObserver;
    NSSet *_dataMigrationBundleIDs;
}

+ (id)sharedInstance;
+ (void)shutdown;
+ (void)deactivate;
+ (void)shrink;
+ (void)cooldown;
+ (void)preheat;
@property(nonatomic) int keybagLockStateNotifyToken; // @synthesize keybagLockStateNotifyToken=_keybagLockStateNotifyToken;
@property(nonatomic) int springBoardLockStateNotifyToken; // @synthesize springBoardLockStateNotifyToken=_springBoardLockStateNotifyToken;
@property(retain, nonatomic) NSSet *dataMigrationBundleIDs; // @synthesize dataMigrationBundleIDs=_dataMigrationBundleIDs;
@property(retain, nonatomic) id <NSObject> dataMigrationFinishObserver; // @synthesize dataMigrationFinishObserver=_dataMigrationFinishObserver;
@property(retain, nonatomic) id <NSObject> dataMigrationStartObserver; // @synthesize dataMigrationStartObserver=_dataMigrationStartObserver;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *firstUnlockTimer; // @synthesize firstUnlockTimer=_firstUnlockTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *firstUnlockQueue; // @synthesize firstUnlockQueue=_firstUnlockQueue;
@property(retain, nonatomic) NSObject<OS_xpc_object> *expirationActivity; // @synthesize expirationActivity=_expirationActivity;
@property(nonatomic) unsigned long long dirty_time; // @synthesize dirty_time=_dirty_time;
@property(retain, nonatomic) NSDictionary *concreteIndexers; // @synthesize concreteIndexers=_concreteIndexers;
@property(nonatomic) _Bool deviceFirstUnlockedInSB; // @synthesize deviceFirstUnlockedInSB=_deviceFirstUnlockedInSB;
@property(nonatomic) _Bool deviceFirstUnlockedInMKB; // @synthesize deviceFirstUnlockedInMKB=_deviceFirstUnlockedInMKB;
@property(nonatomic) unsigned long long dataMigrationStage; // @synthesize dataMigrationStage=_dataMigrationStage;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *reindexAllQueue; // @synthesize reindexAllQueue=_reindexAllQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *indexQueue; // @synthesize indexQueue=_indexQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *idleTimer; // @synthesize idleTimer=_idleTimer;
@property __weak id <CSIndexExtensionDelegate> extensionDelegate; // @synthesize extensionDelegate;
- (void).cxx_destruct;
- (void)runMigration;
- (void)powerStateChanged;
- (void)revokeExpiredItems:(id)arg1;
- (void)fetchAttributesForProtectionClass:(id)arg1 attributes:(id)arg2 bundleID:(id)arg3 identifiers:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)attributesForProtectionClass:(id)arg1 bundleId:(id)arg2 identifier:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)imageDataForProtectionClass:(id)arg1 bundleId:(id)arg2 identifier:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (double)lastUpdateTime;
- (void)performIndexerTask:(id)arg1 withIndexExtensionsAndCompletionHandler:(CDUnknownBlockType)arg2;
- (void)addCompletedBundleIDs:(id)arg1 forIndexerTask:(id)arg2;
- (void)performIndexerTask:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_issueCommand:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)clientDidCheckin:(id)arg1 protectionClass:(id)arg2 service:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)willModifySearchableItemsWithIdentifiers:(id)arg1 protectionClass:(id)arg2 forBundleID:(id)arg3 options:(long long)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)userPerformedAction:(id)arg1 withItem:(id)arg2 protectionClass:(id)arg3 forBundleID:(id)arg4;
- (void)changeStateOfSearchableItemsWithUIDs:(id)arg1 toState:(long long)arg2 protectionClass:(id)arg3 forBundleID:(id)arg4 forUTIType:(id)arg5 options:(long long)arg6;
- (void)fetchLastClientStateWithProtectionClass:(id)arg1 forBundleID:(id)arg2 clientStateName:(id)arg3 options:(long long)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)deleteSearchableItemsSinceDate:(id)arg1 protectionClass:(id)arg2 forBundleID:(id)arg3 options:(long long)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)deleteAllSearchableItemsWithProtectionClass:(id)arg1 forBundleID:(id)arg2 options:(long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)deleteSearchableItemsWithDomainIdentifiers:(id)arg1 protectionClass:(id)arg2 forBundleID:(id)arg3 options:(long long)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)indexSearchableItems:(id)arg1 deleteSearchableItemsWithIdentifiers:(id)arg2 clientState:(id)arg3 clientStateName:(id)arg4 protectionClass:(id)arg5 forBundleID:(id)arg6 options:(long long)arg7 completionHandler:(CDUnknownBlockType)arg8;
- (void)indexSearchableItems:(id)arg1 deleteSearchableItemsWithIdentifiers:(id)arg2 clientState:(id)arg3 protectionClass:(id)arg4 forBundleID:(id)arg5 options:(long long)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)indexFromBundle:(id)arg1 protectionClass:(id)arg2 options:(long long)arg3 items:(id)arg4 itemsText:(id)arg5 itemsHTML:(id)arg6 clientState:(id)arg7 clientStateName:(id)arg8 deletes:(id)arg9 completionHandler:(CDUnknownBlockType)arg10;
- (_Bool)blacklistCheck:(id)arg1;
- (int)openIndex:(_Bool)arg1;
- (int)_openIndex:(_Bool)arg1;
- (void)reindexAllItemsWithIndexers:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)cancelQuery:(id)arg1;
- (id)startQuery:(id)arg1 options:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)dirty;
- (void)closeIndex;
- (void)shrink;
- (void)coolDown;
- (void)issueRepair:(id)arg1;
- (void)issueMerge:(id)arg1;
- (void)issueSplit:(id)arg1;
- (_Bool)commitUpdates;
- (_Bool)flush;
- (void)preheat;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

