//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SDModernSearchDatastore.h"

@class NSDictionary, NSString, _DECConsumer;

@interface SPDefaultSearchDatastore : NSObject <SDModernSearchDatastore>
{
    _DECConsumer *_consumer;
}

- (void).cxx_destruct;
- (void)sendFeedback:(id)arg1;
- (id)displayIdentifierForDomain:(unsigned int)arg1;
- (id)searchDomains;
- (id)performQuery:(id)arg1;
- (void)addApplicationResults:(id)arg1 toSection:(id)arg2;
- (void)addApplicationDeeplinkResults:(id)arg1 toSection:(id)arg2;
- (void)addPersonResults:(id)arg1 toSection:(id)arg2;
- (_Bool)onlyDefaultSearch;
- (_Bool)offersDefaultSearch;
- (void)deactivate;
- (void)activate;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(retain, nonatomic) NSDictionary *category_stats;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

