//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PRSInstalledAppsDataSourceDelegate.h"
#import "PRSSessionController.h"
#import "SDModernSearchDatastore.h"

@class NSArray, NSDictionary, NSObject<OS_dispatch_queue>, NSSet, NSString, NSURLSessionConfiguration, PRSSearchSession;

@interface SPParsecDatastore : NSObject <PRSSessionController, PRSInstalledAppsDataSourceDelegate, SDModernSearchDatastore>
{
    _Bool _activated;
    PRSSearchSession *_session;
    struct __MDSimpleQueryEvaluator *_queryEval;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_feedbackQueue;
    double _sessionStartTime;
    NSDictionary *_cep_server_values;
}

+ (void)initialize;
@property(readonly, nonatomic) NSDictionary *cep_server_values; // @synthesize cep_server_values=_cep_server_values;
@property(nonatomic) double sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
@property _Bool activated; // @synthesize activated=_activated;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *feedbackQueue; // @synthesize feedbackQueue=_feedbackQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) struct __MDSimpleQueryEvaluator *queryEval; // @synthesize queryEval=_queryEval;
@property(retain, nonatomic) PRSSearchSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)shrink;
@property(readonly) NSSet *appBlacklist;
- (long long)getCategoryScoreToReturnInFeedback;
- (id)rankingKnobs;
- (id)cepData;
- (id)cannedCEPValues;
- (id)getCepServerValues;
- (void)setCepServerValues:(id)arg1;
- (void)fetchCardDataFromURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getFTEStringsWithReply:(CDUnknownBlockType)arg1;
- (id)installedApps;
- (void)sendFeedback:(id)arg1;
- (void)sessionReceivedBagWithEnabledDomains:(id)arg1;
- (void)imageDataForIdentifier:(id)arg1 domain:(unsigned int)arg2 size:(struct CGSize)arg3 completion:(CDUnknownBlockType)arg4;
- (id)displayIdentifierForDomain:(unsigned int)arg1;
- (double)timeOutForDomain:(unsigned int)arg1;
- (id)searchDomains;
- (void)shutDown;
- (_Bool)coolDown;
- (void)preheat;
- (void)deactivate;
- (void)activate;
- (id)performQuery:(id)arg1;
@property(readonly, nonatomic) NSURLSessionConfiguration *urlSessionConfiguration;
@property(readonly, nonatomic) NSArray *excludedDomainIdentifiers;
@property(readonly, nonatomic) NSArray *supportedDomainIdentifiers;
@property(readonly, nonatomic) long long useLedBelly;
- (_Bool)isWebSearchEnabled;
@property(readonly, nonatomic, getter=isEnabled) _Bool enabled;
@property(readonly, nonatomic) NSString *applicationNameForUserAgent;
@property(readonly, nonatomic) NSString *parsecBaseURL;
- (_Bool)offersDefaultSearch;
- (id)init;
@property(readonly, nonatomic) long long useSprite;

// Remaining properties
@property(retain, nonatomic) NSDictionary *category_stats;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) _Bool useGUID;
@property(retain, nonatomic) NSString *userId;

@end

