//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PRSSearchQueryHandler.h"
#import "SDSearchToken.h"

@class NSArray, NSDictionary, NSObject<OS_dispatch_queue>, NSString, PRSQueryTask, SDSearchQuery, SPParsecDatastore;

@interface SPParsecQueryTask : NSObject <PRSSearchQueryHandler, SDSearchToken>
{
    NSArray *_rankingPatterns;
    _Bool _canceled;
    _Bool _done;
    _Bool _parsecLoaded;
    _Bool _webSearchLoaded;
    SPParsecDatastore *_store;
    NSDictionary *_category_stats;
    NSString *_fbq;
    NSString *_web_fbq;
    NSObject<OS_dispatch_queue> *_queue;
    SDSearchQuery *_resultPipe;
    PRSQueryTask *_parsecQuery;
    PRSQueryTask *_webSearchQuery;
    NSArray *_parsecResults;
    NSArray *_webSearchResults;
    NSArray *_parsecResultsCategoryOrder;
    unsigned long long _startTime;
}

+ (id)getLastReceivedCategoryStats;
@property unsigned long long startTime; // @synthesize startTime=_startTime;
@property _Bool webSearchLoaded; // @synthesize webSearchLoaded=_webSearchLoaded;
@property _Bool parsecLoaded; // @synthesize parsecLoaded=_parsecLoaded;
@property(retain) NSArray *parsecResultsCategoryOrder; // @synthesize parsecResultsCategoryOrder=_parsecResultsCategoryOrder;
@property(retain) NSArray *webSearchResults; // @synthesize webSearchResults=_webSearchResults;
@property(retain) NSArray *parsecResults; // @synthesize parsecResults=_parsecResults;
@property(retain) PRSQueryTask *webSearchQuery; // @synthesize webSearchQuery=_webSearchQuery;
@property(retain) PRSQueryTask *parsecQuery; // @synthesize parsecQuery=_parsecQuery;
@property _Bool done; // @synthesize done=_done;
@property _Bool canceled; // @synthesize canceled=_canceled;
@property(nonatomic) __weak SDSearchQuery *resultPipe; // @synthesize resultPipe=_resultPipe;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly) NSString *web_fbq; // @synthesize web_fbq=_web_fbq;
@property(readonly) NSString *fbq; // @synthesize fbq=_fbq;
@property(retain, nonatomic) NSDictionary *category_stats; // @synthesize category_stats=_category_stats;
@property(readonly) SPParsecDatastore *store; // @synthesize store=_store;
- (void).cxx_destruct;
- (id)getCepServerValues;
- (unsigned long long)calculateScoreForResult:(id)arg1;
- (long long)matchQualityForAttribute:(id)arg1 queryString:(id)arg2;
- (id)parsecResultsOrder;
- (void)createParsecResultOrder;
- (void)query:(id)arg1 didFinishWithResults:(id)arg2;
- (void)_setScore:(unsigned long long)arg1 forResult:(id)arg2;
- (void)queryDidFinishLoading:(id)arg1;
- (id)createObjectForProtocol:(id)arg1;
- (void)cancel;
- (void)finished;
- (void)setRankingQueries:(id)arg1;
- (id)initWithStore:(id)arg1 resultPipe:(id)arg2 queue:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

